name: Bug Report
description: File a bug report.
title: '[BUG]: '
labels:
  - bug

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for a similar issue in this repository and did not find one.
          required: true

  - type: input
    id: version
    attributes:
      label: PvZ Version
      description: Please ensure you are on the latest version before making an issue.
      placeholder: e.g. v1.1.5-251201
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Model
      placeholder: e.g. Google Pixel 4
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: e.g. Android 12
    validations:
      required: true

  - type: textarea
    id: describe
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: expect
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
